### PR TITLE
Make repo compliant

### PR DESCRIPTION
**Pull request by RaphaelVogel**
**How to categorize this PR?**
/area compliance
/kind cleanup
/platform equinix-metal

**What this PR does / why we need it**:
* Deleted `NOTICE.md` file
* Updated `CONTRIBUTING.md` file
* Created/Updated `LICENSE` file
  * Deleted `LICENSE.md` file
* Created/Updated `.reuse/dep5` file
* Regeneration of `example/controller-registration.yaml` to include new header 
* Created/Updated `LICENSES` folder
* Added badge for reuse compliance in `README.md` file and registered repo with REUSE API
* License/Copyright header replacement for 'non-go' files
  * Makefile
  * hack/update-github-templates.sh
  * hack/hook-me.sh
  * hack/update-codegen.sh
* License/Copyright header replacement for 'go' files
  * cmd/gardener-extension-provider-equinix-metal/main.go
  * cmd/gardener-extension-provider-equinix-metal/app/app.go
  * test/integration/healthcheck/test.go
  * example/doc.go
  * charts/charts.go
  * charts/gardener-extension-provider-equinix-metal/doc.go
  * hack/tools.go
  * imagevector/imagevector.go
  * pkg/webhook/controlplaneexposure/add.go
  * pkg/webhook/controlplaneexposure/ensurer.go
  * pkg/webhook/controlplaneexposure/ensurer_test.go
  * pkg/webhook/controlplane/add.go
  * pkg/webhook/controlplane/mutator.go
  * pkg/webhook/controlplane/ensurer.go
  * pkg/webhook/controlplane/ensurer_test.go
  * pkg/webhook/shoot/add.go
  * pkg/webhook/shoot/metrics_server_test.go
  * pkg/webhook/shoot/vpn_shoot.go
  * pkg/webhook/shoot/vpn_shoot_test.go
  * pkg/webhook/shoot/metrics_server.go
  * pkg/webhook/shoot/shoot_suite_test.go
  * pkg/cmd/config.go
  * pkg/cmd/options.go
  * pkg/apis/config/register.go
  * pkg/apis/config/types.go
  * pkg/apis/config/doc.go
  * pkg/apis/config/install/install.go
  * pkg/apis/config/loader/loader.go
  * pkg/apis/config/v1alpha1/register.go
  * pkg/apis/config/v1alpha1/types.go
  * pkg/apis/config/v1alpha1/defaults.go
  * pkg/apis/config/v1alpha1/doc.go
  * pkg/apis/equinixmetal/register.go
  * pkg/apis/equinixmetal/types_infrastructure.go
  * pkg/apis/equinixmetal/types_controlplane.go
  * pkg/apis/equinixmetal/types_worker.go
  * pkg/apis/equinixmetal/doc.go
  * pkg/apis/equinixmetal/types_cloudprofile.go
  * pkg/apis/equinixmetal/install/install.go
  * pkg/apis/equinixmetal/v1alpha1/register.go
  * pkg/apis/equinixmetal/v1alpha1/types_infrastructure.go
  * pkg/apis/equinixmetal/v1alpha1/types_controlplane.go
  * pkg/apis/equinixmetal/v1alpha1/defaults.go
  * pkg/apis/equinixmetal/v1alpha1/types_worker.go
  * pkg/apis/equinixmetal/v1alpha1/doc.go
  * pkg/apis/equinixmetal/v1alpha1/types_cloudprofile.go
  * pkg/apis/equinixmetal/helper/helper_test.go
  * pkg/apis/equinixmetal/helper/helper.go
  * pkg/apis/equinixmetal/helper/helper_suite_test.go
  * pkg/apis/equinixmetal/validation/cloudprofile_test.go
  * pkg/apis/equinixmetal/validation/validation_suite_test.go
  * pkg/apis/equinixmetal/validation/cloudprofile.go
  * pkg/equinixmetal/equinixmetal_suite_test.go
  * pkg/equinixmetal/types.go
  * pkg/equinixmetal/secret.go
  * pkg/equinixmetal/predicate.go
  * pkg/equinixmetal/secret_test.go
  * pkg/equinixmetal/client/types.go
  * pkg/equinixmetal/client/client.go
  * pkg/controller/healthcheck/add.go
  * pkg/controller/controlplane/controlplane_suite_test.go
  * pkg/controller/controlplane/add.go
  * pkg/controller/controlplane/valuesprovider.go
  * pkg/controller/controlplane/valuesprovider_test.go
  * pkg/controller/worker/add.go
  * pkg/controller/worker/machine_controller_manager.go
  * pkg/controller/worker/worker_suite_test.go
  * pkg/controller/worker/machines.go
  * pkg/controller/worker/helper.go
  * pkg/controller/worker/machines_test.go
  * pkg/controller/worker/actuator.go
  * pkg/controller/worker/machine_dependencies.go
  * pkg/controller/worker/machine_images.go
  * pkg/controller/infrastructure/actuator_delete.go
  * pkg/controller/infrastructure/add.go
  * pkg/controller/infrastructure/terraform.go
  * pkg/controller/infrastructure/actuator_reconcile.go
  * pkg/controller/infrastructure/actuator_reconcile_test.go
  * pkg/controller/infrastructure/actuator_restore.go
  * pkg/controller/infrastructure/infrastructure_suite_test.go
  * pkg/controller/infrastructure/actuator_migrate.go
  * pkg/controller/infrastructure/actuator.go
  * pkg/version/version.go
  * test/integration/suites/run_suite_test.go
  * pkg/webhook/shoot/mutator.go
  * pkg/apis/equinixmetal/helper/scheme.go

**Additional information**
To keep this repository compliant, CODEOWNERS must maintain their third party dependencies in the vendor folder using `.reuse/dep5` file. To prevent constant maintenance effort, it is **highly recommended** to remove the `vendor` folder. In this case no third party dependencies of the vendor folder must be maintained anymore!

### CODE REVIEW

**Review by schrodit — DISMISSED** [review]
/lgtm

**Comment by schrodit** [comment]
@RaphaelVogel the verify setp fails. Please run revendor.

**Comment by RaphaelVogel** [comment]
@schrodit  Done

**Review by schrodit — APPROVED** [review]

**Pull request merged**
