### PR TITLE
Switch from GCR to GAR

### PR DESCRIPTION
**Pull request by zkdev**
**What this PR does / why we need it**:
Adjusts pipeline(s) to publish images and OCM-component-descriptors to `Google Artifact Registry`, rather than `Google Container Registry`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```breaking operator
Change OCI Image Registry from GCR (`eu.gcr.io/gardener-project`) to Artifact-Registry (`europe-docker.pkg.dev/gardener-project/releases`). Users should update their references.
```

### CODE REVIEW

**Review by schrodit — DISMISSED** [review]
/lgtm

**Comment by zkdev** [comment]
https://github.com/gardener/gardener-extension-provider-equinix-metal/commit/78e526630630bfca28b0931ae80170d2549c51f4 needs to be pushed to `refs/meta/ci` once this PR is merged.
Cannot create PR for that due to GitHub limitations 😅

**Comment by schrodit** [comment]
@zkdev you have to re-generate the `controller-registration` due to the image change.

Can you just run `make generate` and push does changes to the PR?

**Comment by zkdev** [comment]
`verify` step succeeded

**Comment by schrodit** [comment]
@zkdev seems like still theold config is used.

but I guess the ci config needs to be merged to reflect the changes?

**Comment by zkdev** [comment]
> but I guess the ci config needs to be merged to reflect the changes?

Yes, the [required config reference](https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/302/commits/be8805c0cda5c8d0bfb9b39a79bf415575c196c6#diff-f6d7f429b1dea52fac85480a4d09b40a781726c59a82705f6e7b2af33972b2cbR11) is changed within this PR.

For more context:
We migrated from GCR to GAR and updated configs to only be privileged for GAR uploads.
As pipelines are rendered from default branch and configs are already changed (w.r.t. upload permissions), this PR verification build will never succeed.

-> It it safe to merge this PR.

**Comment by schrodit** [comment]
@zkdev I do not have permissions to merge the PR without passing the required checks.

@ccwienk or @rfranzke can you force merge this PR?

**Review by schrodit — APPROVED** [review]

**Comment by zkdev** [comment]
[head-update](https://concourse.ci.gardener.cloud/teams/gardener-public/pipelines/gardener-extension-provider-equinix-metal-master/jobs/master-head-update-job/builds/3) got green 🥳

**Pull request merged**
