### PR TITLE
guide how to develop the Packet extension

### PR DESCRIPTION
**Pull request by deitch**
Signed-off-by: Avi Deitcher <avi@deitcher.net>

**How to categorize this PR?**

/area documentation
/kind enhancement
/priority normal
/platform equinix-metal

**What this PR does / why we need it**:

Describes the flow to contribute to and work wth the Equinix Metal extension.

**Release note**:

```doc developer
describe how to contribute to the extension
```

### CODE REVIEW

**Comment by gardener-robot-ci-2** [comment]
Thank you @deitch for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by rfranzke — APPROVED** [review]
/lgtm
/reviewed ok-to-test

**Review by timebertt — APPROVED** [review]
Very nice, @deitch!
/lgtm

**Comment by deitch** [comment]
Thanks @timebertt ; most of the work was by @johananl. I just cleaned it up a bit and upstreamed it.

**Pull request merged**
