### PR TITLE
adding statefulsets in rbac

### PR DESCRIPTION
**Pull request by sltet**
Allowing the extension to list statefulsets in API group "apps" at the cluster scope.

Fixing the following error:
```
E0924 18:22:26.456990       1 reflector.go:153] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:serviceaccount:extension-provider-packet-bfng9:gardener-extension-provider-packet" cannot list resource "statefulsets" in API group "apps" at the cluster scope
```

**How to categorize this PR?**

/area control-plane
/kind bug
/priority normal

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @sltet for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Review by vpnachev — CHANGES_REQUESTED** [review]
Please, run `make generate` and then update this PR.

**Comment by sltet** [comment]
`make generate` is not working for me. seems like there is some issues with tar on macos with --sort=name.

**Comment by rfranzke** [comment]
@sltet you might want to run `make install-requirements` to install the necessary prerequisites

**Review by rfranzke — APPROVED** [review]
/lgtm

**Review by vpnachev — APPROVED** [review]
/lgtm

**Pull request merged**
