### PR TITLE
Fix MetalLB chart description

### PR DESCRIPTION
**Pull request by johananl**
**How to categorize this PR?**

/kind cleanup
/priority normal

**What this PR does / why we need it**:

This is a cleanup for #100. I've copy-pasted the `Chart.yaml` file and forgot to change the description.

**Release note**:

```other operator
NONE
```

### CODE REVIEW

**Comment by gardener-robot-ci-3** [comment]
Thank you @johananl for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by johananl** [comment]
A related general question:

Looks like we create and manage extension-specific charts even for components which have upstream charts. It also seems the chart's `version` field is kept at `0.1.0` even when changes are made to the chart's contents.

Is this the way things are expected to be done? Is Helm used simply as a "wrapper" around YAML files without relying on its versioning etc.? I just want to verify my contribution in #100 is sane and doesn't break any existing Gardener pattern.

Thanks! :pray:

**Review by vpnachev — APPROVED** [review]
/lgtm
/ok-to-test

Gardener has implemented some [utilities](https://github.com/gardener/gardener/tree/master/pkg/utils/chart) to render and apply charts without tiller, it is using helm charts syntax to define the components it deploys. The provider extensions are also using the same concept. 
To be honest, I think we are using everywhere the version `0.1.0` but it should not be a problem to change it.

Recently, we started replacing the charts with go code, more details here https://github.com/gardener/gardener/issues/2754.

**Comment by johananl** [comment]
Thanks for the explanation @vpnachev!

**Pull request merged**
